const { Client } = require('pg');

const NEON_URL = process.env.NEON_DIRECT_URL;
if (!NEON_URL) {
  console.error(
    '错误：未设置 NEON_DIRECT_URL 环境变量。\n' +
      '请设置你的 Neon Direct 连接串（用于初始化建表灌数据）。\n' +
      '在 cubejs-server 目录运行：\n' +
      '  NEON_DIRECT_URL="postgresql://user:pass@host:5432/neondb" node init-db.js'
  );
  process.exit(1);
}

const insertCustomer = 'INSERT INTO customers (name, city, region) VALUES ($1, $2, $3)';
const insertProduct = 'INSERT INTO products (name, category, price) VALUES ($1, $2, $3)';
const insertOrder =
  'INSERT INTO orders (order_date, customer_id, product_id, amount, quantity, region, status) ' +
  'VALUES ($1, $2, $3, $4, $5, $6, $7)';

const customers = [
  ['张三', '北京', '华北'],
  ['李四', '上海', '华东'],
  ['王五', '广州', '华南'],
  ['赵六', '深圳', '华南'],
  ['孙七', '杭州', '华东'],
  ['周八', '成都', '西南'],
  ['吴九', '武汉', '华中'],
  ['郑十', '西安', '西北'],
  ['钱十一', '南京', '华东'],
  ['冯十二', '重庆', '西南'],
];

const products = [
  ['笔记本电脑', '电子产品', 6999],
  ['智能手机', '电子产品', 3999],
  ['无线耳机', '电子产品', 599],
  ['办公桌椅', '办公家具', 1299],
  ['人体工学椅', '办公家具', 2499],
  ['桌面台灯', '办公家具', 299],
  ['Java编程思想', '图书', 99],
  ['设计模式', '图书', 79],
  ['机器学习导论', '图书', 129],
  ['机械键盘', '数码配件', 399],
];

function mulberry32(a) {
  return function () {
    a |= 0;
    a = a + 0x6D2B79F5 | 0;
    var t = Math.imul(a ^ a >>> 15, 1 | a);
    t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}

const statuses = ['completed', 'shipped', 'pending', 'cancelled'];
const regions = ['华北', '华东', '华南', '华中', '西南', '西北'];

async function main() {
  const client = new Client({ connectionString: NEON_URL });
  await client.connect();
  console.log('Connected to Neon.');

  // 清理旧数据（按依赖顺序删表，避免外键问题）
  await client.query('DROP TABLE IF EXISTS orders CASCADE');
  await client.query('DROP TABLE IF EXISTS products CASCADE');
  await client.query('DROP TABLE IF EXISTS customers CASCADE');

  await client.query(`CREATE TABLE customers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    city TEXT NOT NULL,
    region TEXT NOT NULL
  )`);

  await client.query(`CREATE TABLE products (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    price DOUBLE PRECISION NOT NULL
  )`);

  await client.query(`CREATE TABLE orders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date TEXT NOT NULL,
    customer_id INT NOT NULL,
    product_id INT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    quantity INT NOT NULL,
    region TEXT NOT NULL,
    status TEXT NOT NULL
  )`);

  await client.query('CREATE INDEX idx_orders_region ON orders(region)');
  await client.query('CREATE INDEX idx_orders_date ON orders(order_date)');
  await client.query('CREATE INDEX idx_orders_status ON orders(status)');

  console.log('Tables created.');

  // 批量插入 customers
  await client.query('BEGIN');
  for (const c of customers) {
    await client.query(insertCustomer, c);
  }
  await client.query('COMMIT');

  // 批量插入 products
  await client.query('BEGIN');
  for (const p of products) {
    await client.query(insertProduct, p);
  }
  await client.query('COMMIT');

  // 生成并批量插入 orders（固定种子，数据与本地 data.db 完全一致）
  const rand = mulberry32(42);
  const allDates = [];
  const startDate = new Date('2023-01-01');
  const endDate = new Date('2024-12-31');
  for (let d = new Date(startDate); d <= endDate; d = new Date(d.getTime() + 86400000)) {
    allDates.push(d.toISOString().split('T')[0]);
  }
  console.log(`Generating orders for ${allDates.length} days...`);

  let orderCount = 0;
  for (const date of allDates) {
    const numOrders = Math.floor(rand() * 15) + 5;
    await client.query('BEGIN');
    for (let i = 0; i < numOrders; i++) {
      await client.query(
        insertOrder,
        [
          date,
          Math.floor(rand() * 10) + 1,
          Math.floor(rand() * 10) + 1,
          parseFloat((rand() * 5000 + 100).toFixed(2)),
          Math.floor(rand() * 5) + 1,
          regions[Math.floor(rand() * regions.length)],
          statuses[Math.floor(rand() * statuses.length)],
        ]
      );
      orderCount++;
    }
    await client.query('COMMIT');
  }
  console.log(`Total orders: ${orderCount}`);

  const stats = await client.query(
    'SELECT COUNT(*) as cnt, MIN(order_date) as min_d, MAX(order_date) as max_d FROM orders'
  );
  const s = stats.rows[0];
  console.log(
    `Database initialized: ${customers.length} customers, ` +
      `${products.length} products, ${s.cnt} orders\n` +
      `Date range: ${s.min_d} to ${s.max_d}`
  );

  await client.end();
  console.log('Done.');
}

main().catch((err) => {
  console.error('初始化失败：', err);
  process.exit(1);
});
