-- ============================================================
-- Cattle Feedlot Probiotic Trial Database
-- Schema for R-Bot AI Chatbot (Cube.js analytics backend)
-- ============================================================
-- This schema replaces the generic retail schema (customers /
-- products / orders) with domain-specific tables for cattle
-- feedlot probiotic field trials.
-- ============================================================

-- Drop existing tables (dependency order to avoid FK issues)
DROP TABLE IF EXISTS trial_references CASCADE;
DROP TABLE IF EXISTS trial_results       CASCADE;
DROP TABLE IF EXISTS trial_parameters    CASCADE;
DROP TABLE IF EXISTS trials              CASCADE;
DROP TABLE IF EXISTS customer_visits     CASCADE;
DROP TABLE IF EXISTS publications        CASCADE;
DROP TABLE IF EXISTS products            CASCADE;
DROP TABLE IF EXISTS customers           CASCADE;
DROP TABLE IF EXISTS sales_reps          CASCADE;
DROP TABLE IF EXISTS regions             CASCADE;

-- ============================================================
-- 1. regions
-- ============================================================
CREATE TABLE regions (
  id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  TEXT NOT NULL UNIQUE,
  code  TEXT,
  desc  TEXT
);

-- ============================================================
-- 2. sales_reps
-- ============================================================
CREATE TABLE sales_reps (
  id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL,
  email        TEXT,
  phone        TEXT,
  region_id    INT NOT NULL,
  region       TEXT NOT NULL,
  territory    TEXT
);

-- ============================================================
-- 3. customers  (feedlots / cattle operations)
-- ============================================================
CREATE TABLE customers (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  city          TEXT NOT NULL,
  state         TEXT NOT NULL,
  zip           TEXT,
  region        TEXT NOT NULL,
  contact_name  TEXT,
  contact_title TEXT,
  head_count    INT,
  notes         TEXT
);

-- ============================================================
-- 4. products  (probiotic / nutritional products)
-- ============================================================
CREATE TABLE products (
  id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL,
  category     TEXT NOT NULL,
  description  TEXT,
  dosage_unit  TEXT,
  dosage_rate  TEXT
);

-- ============================================================
-- 5. trials  (field trial studies)
-- ============================================================
CREATE TABLE trials (
  id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trial_name      TEXT NOT NULL,
  trial_type      TEXT NOT NULL,
  product_id      INT NOT NULL,
  product_name    TEXT NOT NULL,
  customer_id     INT NOT NULL,
  customer_name   TEXT NOT NULL,
  start_date      TEXT NOT NULL,
  end_date        TEXT,
  duration_days   INT,
  location        TEXT,
  status          TEXT NOT NULL,
  description     TEXT
);

-- ============================================================
-- 6. trial_results  (EAV metrics per trial)
-- ============================================================
CREATE TABLE trial_results (
  id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trial_id         INT NOT NULL,
  trial_name       TEXT NOT NULL,
  group_type       TEXT NOT NULL,
  metric_name      TEXT NOT NULL,
  metric_value     DOUBLE PRECISION NOT NULL,
  unit             TEXT,
  sample_size      INT,
  p_value          DOUBLE PRECISION,
  notes            TEXT
);

-- ============================================================
-- 7. trial_parameters  (environmental / management conditions)
-- ============================================================
CREATE TABLE trial_parameters (
  id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trial_id     INT NOT NULL,
  trial_name   TEXT NOT NULL,
  param_name   TEXT NOT NULL,
  param_value  TEXT NOT NULL,
  unit         TEXT,
  notes        TEXT
);

-- ============================================================
-- 8. publications  (industry research papers & references)
-- ============================================================
CREATE TABLE publications (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       TEXT NOT NULL,
  authors     TEXT,
  journal     TEXT,
  year        INT,
  volume      TEXT,
  pages       TEXT,
  doi         TEXT,
  url         TEXT,
  summary     TEXT,
  relevance   TEXT
);

-- ============================================================
-- 9. trial_references  (N-M link: trials <-> publications)
-- ============================================================
CREATE TABLE trial_references (
  id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trial_id     INT NOT NULL,
  trial_name   TEXT NOT NULL,
  publication_id INT NOT NULL,
  publication_title TEXT NOT NULL,
  citation_note TEXT
);

-- ============================================================
-- customer_visits  (sales rep visits to customers)
-- ============================================================
CREATE TABLE customer_visits (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rep_id        INT NOT NULL,
  rep_name      TEXT NOT NULL,
  customer_id   INT NOT NULL,
  customer_name TEXT NOT NULL,
  visit_date    TEXT NOT NULL,
  purpose       TEXT,
  notes         TEXT
);

-- ============================================================
-- Indexes
-- ============================================================
CREATE INDEX idx_trials_product       ON trials(product_name);
CREATE INDEX idx_trials_customer      ON trials(customer_name);
CREATE INDEX idx_trials_type          ON trials(trial_type);
CREATE INDEX idx_trials_status        ON trials(status);
CREATE INDEX idx_trials_start_date    ON trials(start_date);
CREATE INDEX idx_trial_results_trial  ON trial_results(trial_id);
CREATE INDEX idx_trial_results_metric ON trial_results(metric_name);
CREATE INDEX idx_trial_results_group  ON trial_results(group_type);
CREATE INDEX idx_trial_params_trial   ON trial_parameters(trial_id);
CREATE INDEX idx_trial_refs_trial     ON trial_references(trial_id);
CREATE INDEX idx_trial_refs_pub       ON trial_references(publication_id);
CREATE INDEX idx_customers_city       ON customers(city);
CREATE INDEX idx_customers_state      ON customers(state);
CREATE INDEX idx_visits_customer      ON customer_visits(customer_name);
CREATE INDEX idx_visits_rep           ON customer_visits(rep_name);
